namespace BPOSexplorer
{
	// Token: 0x0200001D RID: 29
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Form : global::System.Windows.Forms.Form
	{
		// Token: 0x06000108 RID: 264 RVA: 0x00034060 File Offset: 0x00032460
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000109 RID: 265 RVA: 0x000340B0 File Offset: 0x000324B0
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BPOSexplorer.Form));
			this.Taskbar = new global::System.Windows.Forms.ToolStrip();
			this.taskbaroptions = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.ProcessesManagerToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator8 = new global::System.Windows.Forms.ToolStripSeparator();
			this.BarSettingsToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripButton1 = new global::System.Windows.Forms.ToolStripDropDownButton();
			this.User2ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.AboutToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator3 = new global::System.Windows.Forms.ToolStripSeparator();
			this.EaseOfAccessToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.OnScreenKeyboardToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.MagnifyToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.NarratorToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.GoogleChromeToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.BPOSSoftwareCenterToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.NotepaderToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.NewExplorerBETAToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator7 = new global::System.Windows.Forms.ToolStripSeparator();
			this.SettingsToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.UsToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator4 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripMenuItem4 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.SearchToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RunToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator1 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ExitToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripSeparator2 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripLabel1 = new global::System.Windows.Forms.ToolStripLabel();
			this.ToolStripButton4 = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripButton2 = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripSeparator5 = new global::System.Windows.Forms.ToolStripSeparator();
			this.ToolStripMenuItem5 = new global::System.Windows.Forms.ToolStripButton();
			this.ToolStripLabel2 = new global::System.Windows.Forms.ToolStripLabel();
			this.ToolStripSeparator6 = new global::System.Windows.Forms.ToolStripSeparator();
			this.userin = new global::System.Windows.Forms.ToolStripLabel();
			this.clocktime = new global::System.Windows.Forms.Timer(this.components);
			this.ToolStripMenuItem1 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripMenuItem2 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripMenuItem3 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripDropDownButton1 = new global::System.Windows.Forms.ToolStripDropDownButton();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.Taskbar.SuspendLayout();
			this.taskbaroptions.SuspendLayout();
			this.SuspendLayout();
			this.Taskbar.ContextMenuStrip = this.taskbaroptions;
			this.Taskbar.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Taskbar.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.ToolStripButton1, this.ToolStripSeparator2, this.ToolStripLabel1, this.ToolStripButton4, this.ToolStripButton2, this.ToolStripSeparator5, this.ToolStripMenuItem5, this.ToolStripLabel2, this.ToolStripSeparator6, this.userin });
			global::System.Windows.Forms.Control taskbar = this.Taskbar;
			global::System.Drawing.Point point = new global::System.Drawing.Point(0, -1);
			taskbar.Location = point;
			this.Taskbar.Name = "Taskbar";
			global::System.Windows.Forms.Control taskbar2 = this.Taskbar;
			global::System.Drawing.Size size = new global::System.Drawing.Size(639, 39);
			taskbar2.Size = size;
			this.Taskbar.TabIndex = 2;
			this.Taskbar.Text = "Fullscreen";
			this.taskbaroptions.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.ProcessesManagerToolStripMenuItem, this.ToolStripSeparator8, this.BarSettingsToolStripMenuItem });
			this.taskbaroptions.Name = "taskbaroptions";
			global::System.Windows.Forms.Control taskbaroptions = this.taskbaroptions;
			size = new global::System.Drawing.Size(169, 76);
			taskbaroptions.Size = size;
			this.ProcessesManagerToolStripMenuItem.Name = "ProcessesManagerToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem processesManagerToolStripMenuItem = this.ProcessesManagerToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			processesManagerToolStripMenuItem.Size = size;
			this.ProcessesManagerToolStripMenuItem.Text = "Start Task Manager";
			this.ToolStripSeparator8.Name = "ToolStripSeparator8";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator = this.ToolStripSeparator8;
			size = new global::System.Drawing.Size(165, 6);
			toolStripSeparator.Size = size;
			this.BarSettingsToolStripMenuItem.Name = "BarSettingsToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem barSettingsToolStripMenuItem = this.BarSettingsToolStripMenuItem;
			size = new global::System.Drawing.Size(168, 22);
			barSettingsToolStripMenuItem.Size = size;
			this.BarSettingsToolStripMenuItem.Text = "Bar Settings";
			this.ToolStripButton1.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.ToolStripButton1.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.User2ToolStripMenuItem, this.AboutToolStripMenuItem, this.ToolStripSeparator3, this.EaseOfAccessToolStripMenuItem, this.GoogleChromeToolStripMenuItem, this.BPOSSoftwareCenterToolStripMenuItem, this.NotepaderToolStripMenuItem, this.NewExplorerBETAToolStripMenuItem, this.ToolStripSeparator7, this.SettingsToolStripMenuItem,
				this.UsToolStripMenuItem, this.ToolStripSeparator4, this.ToolStripMenuItem4, this.SearchToolStripMenuItem, this.RunToolStripMenuItem, this.ToolStripSeparator1, this.ExitToolStripMenuItem
			});
			this.ToolStripButton1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ToolStripButton1.Image");
			this.ToolStripButton1.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.ToolStripButton1.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton1.Name = "ToolStripButton1";
			this.ToolStripButton1.ShowDropDownArrow = false;
			global::System.Windows.Forms.ToolStripItem toolStripButton = this.ToolStripButton1;
			size = new global::System.Drawing.Size(36, 36);
			toolStripButton.Size = size;
			this.ToolStripButton1.Text = "Start";
			this.ToolStripButton1.TextDirection = global::System.Windows.Forms.ToolStripTextDirection.Horizontal;
			this.User2ToolStripMenuItem.BackColor = global::System.Drawing.Color.DodgerBlue;
			this.User2ToolStripMenuItem.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Text;
			this.User2ToolStripMenuItem.Font = new global::System.Drawing.Font("Tahoma", 10f, global::System.Drawing.FontStyle.Bold);
			this.User2ToolStripMenuItem.Name = "User2ToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem user2ToolStripMenuItem = this.User2ToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			user2ToolStripMenuItem.Size = size;
			this.User2ToolStripMenuItem.Text = "user2";
			this.AboutToolStripMenuItem.Name = "AboutToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem aboutToolStripMenuItem = this.AboutToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			aboutToolStripMenuItem.Size = size;
			this.AboutToolStripMenuItem.Text = "About";
			this.ToolStripSeparator3.Name = "ToolStripSeparator3";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator2 = this.ToolStripSeparator3;
			size = new global::System.Drawing.Size(199, 6);
			toolStripSeparator2.Size = size;
			this.EaseOfAccessToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.OnScreenKeyboardToolStripMenuItem, this.MagnifyToolStripMenuItem, this.NarratorToolStripMenuItem });
			this.EaseOfAccessToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("EaseOfAccessToolStripMenuItem.Image");
			this.EaseOfAccessToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.EaseOfAccessToolStripMenuItem.Name = "EaseOfAccessToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem easeOfAccessToolStripMenuItem = this.EaseOfAccessToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			easeOfAccessToolStripMenuItem.Size = size;
			this.EaseOfAccessToolStripMenuItem.Text = "Ease of Access";
			this.OnScreenKeyboardToolStripMenuItem.Name = "OnScreenKeyboardToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem onScreenKeyboardToolStripMenuItem = this.OnScreenKeyboardToolStripMenuItem;
			size = new global::System.Drawing.Size(173, 22);
			onScreenKeyboardToolStripMenuItem.Size = size;
			this.OnScreenKeyboardToolStripMenuItem.Text = "On Screen Keyboard";
			this.MagnifyToolStripMenuItem.Name = "MagnifyToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem magnifyToolStripMenuItem = this.MagnifyToolStripMenuItem;
			size = new global::System.Drawing.Size(173, 22);
			magnifyToolStripMenuItem.Size = size;
			this.MagnifyToolStripMenuItem.Text = "Magnify";
			this.NarratorToolStripMenuItem.Name = "NarratorToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem narratorToolStripMenuItem = this.NarratorToolStripMenuItem;
			size = new global::System.Drawing.Size(173, 22);
			narratorToolStripMenuItem.Size = size;
			this.NarratorToolStripMenuItem.Text = "Narrator";
			this.GoogleChromeToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("GoogleChromeToolStripMenuItem.Image");
			this.GoogleChromeToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.GoogleChromeToolStripMenuItem.Name = "GoogleChromeToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem googleChromeToolStripMenuItem = this.GoogleChromeToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			googleChromeToolStripMenuItem.Size = size;
			this.GoogleChromeToolStripMenuItem.Text = "Mozilla Firefox";
			this.BPOSSoftwareCenterToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("BPOSSoftwareCenterToolStripMenuItem.Image");
			this.BPOSSoftwareCenterToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.BPOSSoftwareCenterToolStripMenuItem.Name = "BPOSSoftwareCenterToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem bpossoftwareCenterToolStripMenuItem = this.BPOSSoftwareCenterToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			bpossoftwareCenterToolStripMenuItem.Size = size;
			this.BPOSSoftwareCenterToolStripMenuItem.Text = "BP OS Software Center";
			this.NotepaderToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("NotepaderToolStripMenuItem.Image");
			this.NotepaderToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.NotepaderToolStripMenuItem.Name = "NotepaderToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem notepaderToolStripMenuItem = this.NotepaderToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			notepaderToolStripMenuItem.Size = size;
			this.NotepaderToolStripMenuItem.Text = "Notepad";
			this.NewExplorerBETAToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("NewExplorerBETAToolStripMenuItem.Image");
			this.NewExplorerBETAToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.NewExplorerBETAToolStripMenuItem.Name = "NewExplorerBETAToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem newExplorerBETAToolStripMenuItem = this.NewExplorerBETAToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			newExplorerBETAToolStripMenuItem.Size = size;
			this.NewExplorerBETAToolStripMenuItem.Text = "NewExplorer";
			this.ToolStripSeparator7.Name = "ToolStripSeparator7";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator3 = this.ToolStripSeparator7;
			size = new global::System.Drawing.Size(199, 6);
			toolStripSeparator3.Size = size;
			this.SettingsToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("SettingsToolStripMenuItem.Image");
			this.SettingsToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.SettingsToolStripMenuItem.Name = "SettingsToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem settingsToolStripMenuItem = this.SettingsToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			settingsToolStripMenuItem.Size = size;
			this.SettingsToolStripMenuItem.Text = "Settings";
			this.UsToolStripMenuItem.Name = "UsToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem usToolStripMenuItem = this.UsToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			usToolStripMenuItem.Size = size;
			this.UsToolStripMenuItem.Text = "My Battery (Beta)";
			this.ToolStripSeparator4.Name = "ToolStripSeparator4";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator4 = this.ToolStripSeparator4;
			size = new global::System.Drawing.Size(199, 6);
			toolStripSeparator4.Size = size;
			this.ToolStripMenuItem4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ToolStripMenuItem4.Image");
			this.ToolStripMenuItem4.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.ToolStripMenuItem4.Name = "ToolStripMenuItem4";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem = this.ToolStripMenuItem4;
			size = new global::System.Drawing.Size(202, 38);
			toolStripMenuItem.Size = size;
			this.ToolStripMenuItem4.Text = "Help Topics";
			this.SearchToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("SearchToolStripMenuItem.Image");
			this.SearchToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.SearchToolStripMenuItem.Name = "SearchToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem searchToolStripMenuItem = this.SearchToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			searchToolStripMenuItem.Size = size;
			this.SearchToolStripMenuItem.Text = "Search Files";
			this.RunToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("RunToolStripMenuItem.Image");
			this.RunToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.RunToolStripMenuItem.Name = "RunToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem runToolStripMenuItem = this.RunToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			runToolStripMenuItem.Size = size;
			this.RunToolStripMenuItem.Text = "Run";
			this.ToolStripSeparator1.Name = "ToolStripSeparator1";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator5 = this.ToolStripSeparator1;
			size = new global::System.Drawing.Size(199, 6);
			toolStripSeparator5.Size = size;
			this.ExitToolStripMenuItem.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ExitToolStripMenuItem.Image");
			this.ExitToolStripMenuItem.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.ExitToolStripMenuItem.Name = "ExitToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem exitToolStripMenuItem = this.ExitToolStripMenuItem;
			size = new global::System.Drawing.Size(202, 38);
			exitToolStripMenuItem.Size = size;
			this.ExitToolStripMenuItem.Text = "End Session";
			this.ToolStripSeparator2.Name = "ToolStripSeparator2";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator6 = this.ToolStripSeparator2;
			size = new global::System.Drawing.Size(6, 39);
			toolStripSeparator6.Size = size;
			this.ToolStripLabel1.Alignment = global::System.Windows.Forms.ToolStripItemAlignment.Right;
			this.ToolStripLabel1.Name = "ToolStripLabel1";
			global::System.Windows.Forms.ToolStripItem toolStripLabel = this.ToolStripLabel1;
			size = new global::System.Drawing.Size(32, 36);
			toolStripLabel.Size = size;
			this.ToolStripLabel1.Text = "Clock";
			this.ToolStripButton4.Alignment = global::System.Windows.Forms.ToolStripItemAlignment.Right;
			this.ToolStripButton4.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.ToolStripButton4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ToolStripButton4.Image");
			this.ToolStripButton4.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.ToolStripButton4.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton4.Name = "ToolStripButton4";
			global::System.Windows.Forms.ToolStripItem toolStripButton2 = this.ToolStripButton4;
			size = new global::System.Drawing.Size(36, 36);
			toolStripButton2.Size = size;
			this.ToolStripButton4.Text = "Volume";
			this.ToolStripButton2.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Text;
			this.ToolStripButton2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ToolStripButton2.Image");
			this.ToolStripButton2.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripButton2.Name = "ToolStripButton2";
			global::System.Windows.Forms.ToolStripItem toolStripButton3 = this.ToolStripButton2;
			size = new global::System.Drawing.Size(51, 36);
			toolStripButton3.Size = size;
			this.ToolStripButton2.Text = "My apps";
			this.ToolStripSeparator5.Name = "ToolStripSeparator5";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator7 = this.ToolStripSeparator5;
			size = new global::System.Drawing.Size(6, 39);
			toolStripSeparator7.Size = size;
			this.ToolStripMenuItem5.Name = "ToolStripMenuItem5";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem2 = this.ToolStripMenuItem5;
			size = new global::System.Drawing.Size(84, 36);
			toolStripMenuItem2.Size = size;
			this.ToolStripMenuItem5.Text = "Send Feedback";
			this.ToolStripLabel2.Alignment = global::System.Windows.Forms.ToolStripItemAlignment.Right;
			this.ToolStripLabel2.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.ToolStripLabel2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ToolStripLabel2.Image");
			this.ToolStripLabel2.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.ToolStripLabel2.Name = "ToolStripLabel2";
			global::System.Windows.Forms.ToolStripItem toolStripLabel2 = this.ToolStripLabel2;
			size = new global::System.Drawing.Size(32, 36);
			toolStripLabel2.Size = size;
			this.ToolStripLabel2.Text = "Internet Status";
			this.ToolStripLabel2.ToolTipText = "Internet Status";
			this.ToolStripSeparator6.Name = "ToolStripSeparator6";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator8 = this.ToolStripSeparator6;
			size = new global::System.Drawing.Size(6, 39);
			toolStripSeparator8.Size = size;
			this.userin.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Text;
			this.userin.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("userin.Image");
			this.userin.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.userin.Name = "userin";
			global::System.Windows.Forms.ToolStripItem userin = this.userin;
			size = new global::System.Drawing.Size(28, 36);
			userin.Size = size;
			this.userin.Text = "user";
			this.ToolStripMenuItem1.Name = "ToolStripMenuItem1";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem3 = this.ToolStripMenuItem1;
			size = new global::System.Drawing.Size(141, 22);
			toolStripMenuItem3.Size = size;
			this.ToolStripMenuItem1.Text = "Tile Horizontal";
			this.ToolStripMenuItem2.Name = "ToolStripMenuItem2";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem4 = this.ToolStripMenuItem2;
			size = new global::System.Drawing.Size(141, 22);
			toolStripMenuItem4.Size = size;
			this.ToolStripMenuItem2.Text = "Tile Vertical";
			this.ToolStripMenuItem3.Name = "ToolStripMenuItem3";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem5 = this.ToolStripMenuItem3;
			size = new global::System.Drawing.Size(141, 22);
			toolStripMenuItem5.Size = size;
			this.ToolStripMenuItem3.Text = "Cascade";
			this.ToolStripDropDownButton1.DisplayStyle = global::System.Windows.Forms.ToolStripItemDisplayStyle.Text;
			this.ToolStripDropDownButton1.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.ToolStripMenuItem1, this.ToolStripMenuItem2, this.ToolStripMenuItem3 });
			this.ToolStripDropDownButton1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("ToolStripDropDownButton1.Image");
			this.ToolStripDropDownButton1.ImageScaling = global::System.Windows.Forms.ToolStripItemImageScaling.None;
			this.ToolStripDropDownButton1.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.ToolStripDropDownButton1.Name = "ToolStripDropDownButton1";
			global::System.Windows.Forms.ToolStripItem toolStripDropDownButton = this.ToolStripDropDownButton1;
			size = new global::System.Drawing.Size(69, 19);
			toolStripDropDownButton.Size = size;
			this.ToolStripDropDownButton1.Text = "Windows";
			this.Timer1.Interval = 10000000;
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.SystemColors.Control;
			this.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.None;
			size = new global::System.Drawing.Size(639, 38);
			this.ClientSize = size;
			this.ControlBox = false;
			this.Controls.Add(this.Taskbar);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "Form";
			this.ShowIcon = false;
			this.ShowInTaskbar = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.Manual;
			this.Text = "Bob Pony OS Bar";
			this.Taskbar.ResumeLayout(false);
			this.Taskbar.PerformLayout();
			this.taskbaroptions.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x040000F9 RID: 249
		private global::System.ComponentModel.IContainer components;
	}
}
