namespace BPOSexplorer
{
	// Token: 0x02000028 RID: 40
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class pane : global::System.Windows.Forms.Form
	{
		// Token: 0x0600024E RID: 590 RVA: 0x0003AB44 File Offset: 0x00038F44
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600024F RID: 591 RVA: 0x0003AB94 File Offset: 0x00038F94
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BPOSexplorer.pane));
			this.LinkLabel1 = new global::System.Windows.Forms.LinkLabel();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.LinkLabel2 = new global::System.Windows.Forms.LinkLabel();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.LinkLabel3 = new global::System.Windows.Forms.LinkLabel();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.LinkLabel4 = new global::System.Windows.Forms.LinkLabel();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.LinkLabel5 = new global::System.Windows.Forms.LinkLabel();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox5 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox6 = new global::System.Windows.Forms.PictureBox();
			this.LinkLabel6 = new global::System.Windows.Forms.LinkLabel();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.PictureBox7 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox8 = new global::System.Windows.Forms.PictureBox();
			this.LinkLabel7 = new global::System.Windows.Forms.LinkLabel();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.LinkLabel8 = new global::System.Windows.Forms.LinkLabel();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.PictureBox9 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox10 = new global::System.Windows.Forms.PictureBox();
			this.LinkLabel9 = new global::System.Windows.Forms.LinkLabel();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.PictureBox11 = new global::System.Windows.Forms.PictureBox();
			this.LinkLabel10 = new global::System.Windows.Forms.LinkLabel();
			this.PictureBox12 = new global::System.Windows.Forms.PictureBox();
			this.LinkLabel11 = new global::System.Windows.Forms.LinkLabel();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.LinkLabel17 = new global::System.Windows.Forms.LinkLabel();
			this.LinkLabel15 = new global::System.Windows.Forms.LinkLabel();
			this.LinkLabel14 = new global::System.Windows.Forms.LinkLabel();
			this.LinkLabel13 = new global::System.Windows.Forms.LinkLabel();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox7).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox8).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox9).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox10).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox11).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox12).BeginInit();
			this.GroupBox1.SuspendLayout();
			this.SuspendLayout();
			this.LinkLabel1.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel = this.LinkLabel1;
			global::System.Drawing.Point point = new global::System.Drawing.Point(205, 15);
			linkLabel.Location = point;
			this.LinkLabel1.Name = "LinkLabel1";
			global::System.Windows.Forms.Control linkLabel2 = this.LinkLabel1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(23, 13);
			linkLabel2.Size = size;
			this.LinkLabel1.TabIndex = 0;
			this.LinkLabel1.TabStop = true;
			this.LinkLabel1.Text = "Bar";
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control label = this.Label1;
			point = new global::System.Drawing.Point(205, 36);
			label.Location = point;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(349, 13);
			label2.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "Use this if you want to personalize your Bar in Bob Pony OS to your style!";
			this.LinkLabel2.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel3 = this.LinkLabel2;
			point = new global::System.Drawing.Point(205, 82);
			linkLabel3.Location = point;
			this.LinkLabel2.Name = "LinkLabel2";
			global::System.Windows.Forms.Control linkLabel4 = this.LinkLabel2;
			size = new global::System.Drawing.Size(108, 13);
			linkLabel4.Size = size;
			this.LinkLabel2.TabIndex = 2;
			this.LinkLabel2.TabStop = true;
			this.LinkLabel2.Text = "Desktop Background";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label3 = this.Label2;
			point = new global::System.Drawing.Point(205, 103);
			label3.Location = point;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(323, 13);
			label4.Size = size;
			this.Label2.TabIndex = 3;
			this.Label2.Text = "Personalize your computer even better with a desktop background.";
			this.LinkLabel3.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel5 = this.LinkLabel3;
			point = new global::System.Drawing.Point(205, 144);
			linkLabel5.Location = point;
			this.LinkLabel3.Name = "LinkLabel3";
			global::System.Windows.Forms.Control linkLabel6 = this.LinkLabel3;
			size = new global::System.Drawing.Size(89, 13);
			linkLabel6.Size = size;
			this.LinkLabel3.TabIndex = 4;
			this.LinkLabel3.TabStop = true;
			this.LinkLabel3.Text = "Screen resolution";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label5 = this.Label3;
			point = new global::System.Drawing.Point(206, 165);
			label5.Location = point;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(322, 13);
			label6.Size = size;
			this.Label3.TabIndex = 5;
			this.Label3.Text = "Things not perfect, stretch, or too small? Change screen resolution.";
			this.LinkLabel4.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel7 = this.LinkLabel4;
			point = new global::System.Drawing.Point(205, 202);
			linkLabel7.Location = point;
			this.LinkLabel4.Name = "LinkLabel4";
			global::System.Windows.Forms.Control linkLabel8 = this.LinkLabel4;
			size = new global::System.Drawing.Size(79, 13);
			linkLabel8.Size = size;
			this.LinkLabel4.TabIndex = 6;
			this.LinkLabel4.TabStop = true;
			this.LinkLabel4.Text = "Sound Settings";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label7 = this.Label4;
			point = new global::System.Drawing.Point(205, 223);
			label7.Location = point;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label8 = this.Label4;
			size = new global::System.Drawing.Size(467, 13);
			label8.Size = size;
			this.Label4.TabIndex = 7;
			this.Label4.Text = "Adjust your speakers, tweak speaker settingers, change the sounds you hear like the alert sounds";
			this.LinkLabel5.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel9 = this.LinkLabel5;
			point = new global::System.Drawing.Point(205, 259);
			linkLabel9.Location = point;
			this.LinkLabel5.Name = "LinkLabel5";
			global::System.Windows.Forms.Control linkLabel10 = this.LinkLabel5;
			size = new global::System.Drawing.Size(39, 13);
			linkLabel10.Size = size;
			this.LinkLabel5.TabIndex = 8;
			this.LinkLabel5.TabStop = true;
			this.LinkLabel5.Text = "Mouse";
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			global::System.Windows.Forms.Control pictureBox = this.PictureBox1;
			point = new global::System.Drawing.Point(157, 12);
			pictureBox.Location = point;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control pictureBox2 = this.PictureBox1;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox2.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox1.TabIndex = 9;
			this.PictureBox1.TabStop = false;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			global::System.Windows.Forms.Control pictureBox3 = this.PictureBox2;
			point = new global::System.Drawing.Point(157, 79);
			pictureBox3.Location = point;
			this.PictureBox2.Name = "PictureBox2";
			global::System.Windows.Forms.Control pictureBox4 = this.PictureBox2;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox4.Size = size;
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox2.TabIndex = 10;
			this.PictureBox2.TabStop = false;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			global::System.Windows.Forms.Control pictureBox5 = this.PictureBox3;
			point = new global::System.Drawing.Point(157, 141);
			pictureBox5.Location = point;
			this.PictureBox3.Name = "PictureBox3";
			global::System.Windows.Forms.Control pictureBox6 = this.PictureBox3;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox6.Size = size;
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox3.TabIndex = 11;
			this.PictureBox3.TabStop = false;
			this.PictureBox4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox4.Image");
			global::System.Windows.Forms.Control pictureBox7 = this.PictureBox4;
			point = new global::System.Drawing.Point(157, 199);
			pictureBox7.Location = point;
			this.PictureBox4.Name = "PictureBox4";
			global::System.Windows.Forms.Control pictureBox8 = this.PictureBox4;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox8.Size = size;
			this.PictureBox4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox4.TabIndex = 12;
			this.PictureBox4.TabStop = false;
			this.PictureBox5.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox5.Image");
			global::System.Windows.Forms.Control pictureBox9 = this.PictureBox5;
			point = new global::System.Drawing.Point(157, 256);
			pictureBox9.Location = point;
			this.PictureBox5.Name = "PictureBox5";
			global::System.Windows.Forms.Control pictureBox10 = this.PictureBox5;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox10.Size = size;
			this.PictureBox5.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox5.TabIndex = 13;
			this.PictureBox5.TabStop = false;
			this.PictureBox6.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox6.Image");
			global::System.Windows.Forms.Control pictureBox11 = this.PictureBox6;
			point = new global::System.Drawing.Point(157, 312);
			pictureBox11.Location = point;
			this.PictureBox6.Name = "PictureBox6";
			global::System.Windows.Forms.Control pictureBox12 = this.PictureBox6;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox12.Size = size;
			this.PictureBox6.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox6.TabIndex = 14;
			this.PictureBox6.TabStop = false;
			this.LinkLabel6.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel11 = this.LinkLabel6;
			point = new global::System.Drawing.Point(206, 315);
			linkLabel11.Location = point;
			this.LinkLabel6.Name = "LinkLabel6";
			global::System.Windows.Forms.Control linkLabel12 = this.LinkLabel6;
			size = new global::System.Drawing.Size(72, 13);
			linkLabel12.Size = size;
			this.LinkLabel6.TabIndex = 15;
			this.LinkLabel6.TabStop = true;
			this.LinkLabel6.Text = "Screensavers";
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label9 = this.Label5;
			point = new global::System.Drawing.Point(206, 280);
			label9.Location = point;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label10 = this.Label5;
			size = new global::System.Drawing.Size(301, 13);
			label10.Size = size;
			this.Label5.TabIndex = 16;
			this.Label5.Text = "Do tweaks to your computer mouse, change cursor, and more!";
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label6;
			point = new global::System.Drawing.Point(206, 333);
			label11.Location = point;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label12 = this.Label6;
			size = new global::System.Drawing.Size(316, 13);
			label12.Size = size;
			this.Label6.TabIndex = 17;
			this.Label6.Text = "Recommend for users who use old Computer Monitors/TVs (CRT)";
			this.PictureBox7.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox7.Image");
			global::System.Windows.Forms.Control pictureBox13 = this.PictureBox7;
			point = new global::System.Drawing.Point(157, 368);
			pictureBox13.Location = point;
			this.PictureBox7.Name = "PictureBox7";
			global::System.Windows.Forms.Control pictureBox14 = this.PictureBox7;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox14.Size = size;
			this.PictureBox7.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox7.TabIndex = 18;
			this.PictureBox7.TabStop = false;
			this.PictureBox8.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox8.Image");
			global::System.Windows.Forms.Control pictureBox15 = this.PictureBox8;
			point = new global::System.Drawing.Point(157, 424);
			pictureBox15.Location = point;
			this.PictureBox8.Name = "PictureBox8";
			global::System.Windows.Forms.Control pictureBox16 = this.PictureBox8;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox16.Size = size;
			this.PictureBox8.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox8.TabIndex = 19;
			this.PictureBox8.TabStop = false;
			this.LinkLabel7.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel13 = this.LinkLabel7;
			point = new global::System.Drawing.Point(205, 368);
			linkLabel13.Location = point;
			this.LinkLabel7.Name = "LinkLabel7";
			global::System.Windows.Forms.Control linkLabel14 = this.LinkLabel7;
			size = new global::System.Drawing.Size(127, 13);
			linkLabel14.Size = size;
			this.LinkLabel7.TabIndex = 20;
			this.LinkLabel7.TabStop = true;
			this.LinkLabel7.Text = "Date and Time Properties";
			this.Label7.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label7;
			point = new global::System.Drawing.Point(206, 387);
			label13.Location = point;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label14 = this.Label7;
			size = new global::System.Drawing.Size(211, 13);
			label14.Size = size;
			this.Label7.TabIndex = 21;
			this.Label7.Text = "Change time zone, fix time, and many more!";
			this.LinkLabel8.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel15 = this.LinkLabel8;
			point = new global::System.Drawing.Point(206, 424);
			linkLabel15.Location = point;
			this.LinkLabel8.Name = "LinkLabel8";
			global::System.Windows.Forms.Control linkLabel16 = this.LinkLabel8;
			size = new global::System.Drawing.Size(113, 13);
			linkLabel16.Size = size;
			this.LinkLabel8.TabIndex = 22;
			this.LinkLabel8.TabStop = true;
			this.LinkLabel8.Text = "Region and Language";
			this.Label8.AutoSize = true;
			global::System.Windows.Forms.Control label15 = this.Label8;
			point = new global::System.Drawing.Point(206, 445);
			label15.Location = point;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label16 = this.Label8;
			size = new global::System.Drawing.Size(301, 13);
			label16.Size = size;
			this.Label8.TabIndex = 23;
			this.Label8.Text = "Live in a different country, have a different keyboard, and etc?";
			this.PictureBox9.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox9.Image");
			global::System.Windows.Forms.Control pictureBox17 = this.PictureBox9;
			point = new global::System.Drawing.Point(614, 502);
			pictureBox17.Location = point;
			this.PictureBox9.Name = "PictureBox9";
			global::System.Windows.Forms.Control pictureBox18 = this.PictureBox9;
			size = new global::System.Drawing.Size(128, 128);
			pictureBox18.Size = size;
			this.PictureBox9.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.PictureBox9.TabIndex = 24;
			this.PictureBox9.TabStop = false;
			this.PictureBox10.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox10.Image");
			global::System.Windows.Forms.Control pictureBox19 = this.PictureBox10;
			point = new global::System.Drawing.Point(157, 480);
			pictureBox19.Location = point;
			this.PictureBox10.Name = "PictureBox10";
			global::System.Windows.Forms.Control pictureBox20 = this.PictureBox10;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox20.Size = size;
			this.PictureBox10.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox10.TabIndex = 25;
			this.PictureBox10.TabStop = false;
			this.LinkLabel9.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel17 = this.LinkLabel9;
			point = new global::System.Drawing.Point(209, 480);
			linkLabel17.Location = point;
			this.LinkLabel9.Name = "LinkLabel9";
			global::System.Windows.Forms.Control linkLabel18 = this.LinkLabel9;
			size = new global::System.Drawing.Size(76, 13);
			linkLabel18.Size = size;
			this.LinkLabel9.TabIndex = 26;
			this.LinkLabel9.TabStop = true;
			this.LinkLabel9.Text = "User accounts";
			this.Label9.AutoSize = true;
			global::System.Windows.Forms.Control label17 = this.Label9;
			point = new global::System.Drawing.Point(210, 502);
			label17.Location = point;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label18 = this.Label9;
			size = new global::System.Drawing.Size(227, 13);
			label18.Size = size;
			this.Label9.TabIndex = 27;
			this.Label9.Text = "Have more than 1 person using this computer?";
			this.PictureBox11.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox11.Image");
			global::System.Windows.Forms.Control pictureBox21 = this.PictureBox11;
			point = new global::System.Drawing.Point(157, 536);
			pictureBox21.Location = point;
			this.PictureBox11.Name = "PictureBox11";
			global::System.Windows.Forms.Control pictureBox22 = this.PictureBox11;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox22.Size = size;
			this.PictureBox11.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox11.TabIndex = 28;
			this.PictureBox11.TabStop = false;
			this.LinkLabel10.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel19 = this.LinkLabel10;
			point = new global::System.Drawing.Point(206, 536);
			linkLabel19.Location = point;
			this.LinkLabel10.Name = "LinkLabel10";
			global::System.Windows.Forms.Control linkLabel20 = this.LinkLabel10;
			size = new global::System.Drawing.Size(155, 13);
			linkLabel20.Size = size;
			this.LinkLabel10.TabIndex = 29;
			this.LinkLabel10.TabStop = true;
			this.LinkLabel10.Text = "Window Color and Appearance";
			this.PictureBox12.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox12.Image");
			global::System.Windows.Forms.Control pictureBox23 = this.PictureBox12;
			point = new global::System.Drawing.Point(157, 583);
			pictureBox23.Location = point;
			this.PictureBox12.Name = "PictureBox12";
			global::System.Windows.Forms.Control pictureBox24 = this.PictureBox12;
			size = new global::System.Drawing.Size(42, 41);
			pictureBox24.Size = size;
			this.PictureBox12.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox12.TabIndex = 30;
			this.PictureBox12.TabStop = false;
			this.LinkLabel11.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel21 = this.LinkLabel11;
			point = new global::System.Drawing.Point(209, 583);
			linkLabel21.Location = point;
			this.LinkLabel11.Name = "LinkLabel11";
			global::System.Windows.Forms.Control linkLabel22 = this.LinkLabel11;
			size = new global::System.Drawing.Size(33, 13);
			linkLabel22.Size = size;
			this.LinkLabel11.TabIndex = 31;
			this.LinkLabel11.TabStop = true;
			this.LinkLabel11.Text = "Fonts";
			this.Label10.AutoSize = true;
			global::System.Windows.Forms.Control label19 = this.Label10;
			point = new global::System.Drawing.Point(206, 557);
			label19.Location = point;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label20 = this.Label10;
			size = new global::System.Drawing.Size(285, 13);
			label20.Size = size;
			this.Label10.TabIndex = 32;
			this.Label10.Text = "Make the window color more likable to your style and more!";
			this.Label11.AutoSize = true;
			global::System.Windows.Forms.Control label21 = this.Label11;
			point = new global::System.Drawing.Point(208, 607);
			label21.Location = point;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label22 = this.Label11;
			size = new global::System.Drawing.Size(219, 13);
			label22.Size = size;
			this.Label11.TabIndex = 33;
			this.Label11.Text = "Manage the installed fonts on your computer.";
			this.GroupBox1.Controls.Add(this.LinkLabel17);
			this.GroupBox1.Controls.Add(this.LinkLabel15);
			this.GroupBox1.Controls.Add(this.LinkLabel14);
			this.GroupBox1.Controls.Add(this.LinkLabel13);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			point = new global::System.Drawing.Point(3, 12);
			groupBox.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new global::System.Drawing.Size(148, 612);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 34;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "More";
			this.LinkLabel17.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel23 = this.LinkLabel17;
			point = new global::System.Drawing.Point(9, 88);
			linkLabel23.Location = point;
			this.LinkLabel17.Name = "LinkLabel17";
			global::System.Windows.Forms.Control linkLabel24 = this.LinkLabel17;
			size = new global::System.Drawing.Size(91, 13);
			linkLabel24.Size = size;
			this.LinkLabel17.TabIndex = 5;
			this.LinkLabel17.TabStop = true;
			this.LinkLabel17.Text = "System Properties";
			this.LinkLabel15.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel25 = this.LinkLabel15;
			point = new global::System.Drawing.Point(9, 40);
			linkLabel25.Location = point;
			this.LinkLabel15.Name = "LinkLabel15";
			global::System.Windows.Forms.Control linkLabel26 = this.LinkLabel15;
			size = new global::System.Drawing.Size(95, 13);
			linkLabel26.Size = size;
			this.LinkLabel15.TabIndex = 3;
			this.LinkLabel15.TabStop = true;
			this.LinkLabel15.Text = "Windows Features";
			this.LinkLabel14.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel27 = this.LinkLabel14;
			point = new global::System.Drawing.Point(9, 16);
			linkLabel27.Location = point;
			this.LinkLabel14.Name = "LinkLabel14";
			global::System.Windows.Forms.Control linkLabel28 = this.LinkLabel14;
			size = new global::System.Drawing.Size(86, 13);
			linkLabel28.Size = size;
			this.LinkLabel14.TabIndex = 2;
			this.LinkLabel14.TabStop = true;
			this.LinkLabel14.Text = "Visit Help Topics";
			this.LinkLabel13.AutoSize = true;
			global::System.Windows.Forms.Control linkLabel29 = this.LinkLabel13;
			point = new global::System.Drawing.Point(9, 584);
			linkLabel29.Location = point;
			this.LinkLabel13.Name = "LinkLabel13";
			global::System.Windows.Forms.Control linkLabel30 = this.LinkLabel13;
			size = new global::System.Drawing.Size(83, 13);
			linkLabel30.Size = size;
			this.LinkLabel13.TabIndex = 1;
			this.LinkLabel13.TabStop = true;
			this.LinkLabel13.Text = "Send Feedback";
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(747, 636);
			this.ClientSize = size;
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.Label11);
			this.Controls.Add(this.Label10);
			this.Controls.Add(this.LinkLabel11);
			this.Controls.Add(this.PictureBox12);
			this.Controls.Add(this.LinkLabel10);
			this.Controls.Add(this.PictureBox11);
			this.Controls.Add(this.Label9);
			this.Controls.Add(this.LinkLabel9);
			this.Controls.Add(this.PictureBox10);
			this.Controls.Add(this.PictureBox9);
			this.Controls.Add(this.Label8);
			this.Controls.Add(this.LinkLabel8);
			this.Controls.Add(this.Label7);
			this.Controls.Add(this.LinkLabel7);
			this.Controls.Add(this.PictureBox8);
			this.Controls.Add(this.PictureBox7);
			this.Controls.Add(this.Label6);
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.LinkLabel6);
			this.Controls.Add(this.PictureBox6);
			this.Controls.Add(this.PictureBox5);
			this.Controls.Add(this.PictureBox4);
			this.Controls.Add(this.PictureBox3);
			this.Controls.Add(this.PictureBox2);
			this.Controls.Add(this.PictureBox1);
			this.Controls.Add(this.LinkLabel5);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.LinkLabel4);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.LinkLabel3);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.LinkLabel2);
			this.Controls.Add(this.Label1);
			this.Controls.Add(this.LinkLabel1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MaximizeBox = false;
			this.Name = "pane";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Settings Panel";
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox7).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox8).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox9).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox10).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox11).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox12).EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x04000183 RID: 387
		private global::System.ComponentModel.IContainer components;
	}
}
